[build]
  # Base directory that contains the package.json file
  base    = "/"
  # Directory to change to before starting a build
  publish = "build"
  command = "npm run build"

# Environment settings
[build.environment]
  # Python settings
  PYTHON_VERSION = "3.9"
  # Node.js settings
  NODE_VERSION = "18"  # Updated to LTS version
  NPM_VERSION = "9"    # Updated to match Node 18
  # Environment variables
  NODE_ENV = "production"
  # Ensure Python is not compiled from source
  PYTHON_SETUP_REQUIRES = "pip"
  PIPENV_RUN_BIN = "/opt/buildhome/python3.9/bin"

# For a Python backend, you might need to specify Python requirements
[[plugins]]
  package = "@netlify/plugin-python"

# For a React frontend (adjust based on your actual frontend framework)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA (Single Page Application)
# This ensures all routes work with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for backend requests (adjust the backend URL as needed)
[[redirects]]
  from = "/api/*"
  to = "https://auth.skreenit.com/:splat"  # Replace with your actual backend URL
  status = 200
  force = true

# Add other environment variables here or in Netlify UI

# For Python applications, you might need to specify the Python version
[build.processing]
  skip_processing = false

# For server-side functions (if using Netlify Functions)
[functions]
  # Directory where your Netlify Functions are stored
  directory = "functions/"
  # Node.js version for functions
  node_bundler = "esbuild"

# For build optimization
[build.optimization]
  bundle = true
  minify = true
  target = ["es2017"]

# For build speed improvements
[build.caching]
  # Cache the following directories between builds
  paths = ["node_modules/.cache", ".cache"]
